-- Tenants and the config outbox. Append-only: do not edit this file.
-- Control D1 is the only writer. The data plane receives a copy through pushConfig.
CREATE TABLE IF NOT EXISTS tenants (
  id TEXT PRIMARY KEY,
  name TEXT NOT NULL UNIQUE,
  owner_account_id TEXT NOT NULL,
  status TEXT NOT NULL,
  region TEXT NOT NULL,
  config_json TEXT NOT NULL,
  limits_json TEXT NOT NULL,
  approval_json TEXT NOT NULL,
  owner_token_hash TEXT NOT NULL,
  secrets_enc TEXT,
  config_version INTEGER NOT NULL,
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL
);
CREATE INDEX IF NOT EXISTS tenants_owner_idx ON tenants (owner_account_id);

CREATE TABLE IF NOT EXISTS config_outbox (
  tenant_id TEXT NOT NULL,
  version INTEGER NOT NULL,
  created_at TEXT NOT NULL,
  PRIMARY KEY (tenant_id, version)
);
