-- OpenID Connect issuer keys and per-tenant clients. Append-only: do not edit this file.
-- `jwks` matches Better Auth's JWT plugin (RS256). The private key is encrypted by that plugin.
CREATE TABLE IF NOT EXISTS "jwks" (
  "id" text not null primary key,
  "publicKey" text not null,
  "privateKey" text not null,
  "createdAt" date not null,
  "expiresAt" date,
  "alg" text,
  "crv" text
);

CREATE TABLE IF NOT EXISTS oauth_client (
  id TEXT PRIMARY KEY,
  secret_hash TEXT NOT NULL,
  owner_account_id TEXT NOT NULL,
  redirect_uris TEXT NOT NULL,
  created_at TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS oauth_code (
  code_hash TEXT PRIMARY KEY,
  client_id TEXT NOT NULL,
  user_id TEXT NOT NULL,
  redirect_uri TEXT NOT NULL,
  nonce TEXT NOT NULL,
  challenge TEXT NOT NULL,
  expires_at TEXT NOT NULL,
  used_at TEXT
);
