-- Device authorization codes for CLI sign-in (Better Auth device-authorization plugin).
-- Append-only: do not edit this file.
CREATE TABLE IF NOT EXISTS "deviceCode" (
  "id" text not null primary key,
  "deviceCode" text not null unique,
  "userCode" text not null unique,
  "userId" text,
  "expiresAt" date not null,
  "status" text not null,
  "lastPolledAt" date,
  "pollingInterval" integer,
  "clientId" text,
  "scope" text
);
